include dracula.conf
# include kitty-colors.conf

enable_audio_bell no
font_family family="Fira Code"

dynamic_background_opacity yes

linux_display_server wayland

scrollback_lines 100000

map kitty_mod+1        set_background_opacity +0.1
map kitty_mod+2   set_background_opacity -0.1
map kitty_mod+3          set_background_opacity 1

window_padding_width 4

