# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FED7BB
background         #29282F
cursor             #FED7BB

active_tab_foreground     #29282F
active_tab_background     #FED7BB
inactive_tab_foreground   #FED7BB
inactive_tab_background   #29282F

active_border_color   #FED7BB
inactive_border_color #29282F
bell_border_color     #262135

color0      #4E4D55
color1		#262135
color2		#4E3433
color3		#663940
color4		#814C30
color5		#BD692D
color6		#BD692D
color7		#F5BD95
color8		#AC8468
color9		#322B46
color10		#684544
color11		#884C55
color12		#AB6540
color13		#FC8C3C
color14		#FC8C3C
color15		#F5BD95
