# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(29282F)
$foreground = rgb(FED7BB)
$color0 = rgb(4E4D55)
$color1 = rgb(262135)
$color2 = rgb(4E3433)
$color3 = rgb(663940)
$color4 = rgb(814C30)
$color5 = rgb(BD692D)
$color6 = rgb(BD692D)
$color7 = rgb(F5BD95)
$color8 = rgb(AC8468)
$color9 = rgb(322B46)
$color10 = rgb(684544)
$color11 = rgb(884C55)
$color12 = rgb(AB6540)
$color13 = rgb(FC8C3C)
$color14 = rgb(FC8C3C)
$color15 = rgb(F5BD95)
